/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsc.inf.View;

import Presidente.Constantes;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class TelaMesa extends javax.swing.JFrame {

    protected AtorJogador atorJogador;
   
    
    /**
     * Creates new form TElaMesa
     */
    public TelaMesa(AtorJogador atorJogador) {
        initComponents();
        this.atorJogador = atorJogador;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuConectar = new javax.swing.JMenu();
        jMenuIniciarPartida = new javax.swing.JMenu();
        jMenuDesconectar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jMenuConectar.setText("Conectar");
        jMenuConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuConectarMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuConectar);

        jMenuIniciarPartida.setText("Iniciar Partida");
        jMenuIniciarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuIniciarPartidaMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuIniciarPartida);

        jMenuDesconectar.setText("Desconectar");
        jMenuDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDesconectarMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuDesconectar);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap(989, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(383, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(261, 261, 261))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConectarMouseClicked
        // TODO add your handling code here:
        //Informar que Conectar foi clicado
        this.atorJogador.conectar();
    }//GEN-LAST:event_jMenuConectarMouseClicked

    private void jMenuIniciarPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuIniciarPartidaMouseClicked
        // TODO add your handling code here:
        //Informar que Iniciar partida foi clicado
        this.atorJogador.iniciarPartida();
    }//GEN-LAST:event_jMenuIniciarPartidaMouseClicked

    private void jMenuDesconectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDesconectarMouseClicked
        // TODO add your handling code here:
        this.atorJogador.desconectar();
    }//GEN-LAST:event_jMenuDesconectarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConectar;
    private javax.swing.JMenu jMenuDesconectar;
    private javax.swing.JMenu jMenuIniciarPartida;
    // End of variables declaration//GEN-END:variables

    public void informarResultado(int resultado) {
        switch(resultado){
            case Constantes.CONEXAO_EXITO:
                JOptionPane.showMessageDialog(this, Constantes.CONEXAO_EXITO_STRING);
                break;
            case Constantes.CONEXAO_FALHOU:
                JOptionPane.showMessageDialog(this, Constantes.CONEXAO_FALHOU_STRING);
                break;
            case Constantes.JA_CONECTADO:
                JOptionPane.showMessageDialog(this, Constantes.JA_CONECTADO_STRING);
                break;
            case Constantes.DESCONEXAO_EXITO:
                JOptionPane.showMessageDialog(this, Constantes.DESCONEXAO_EXITO_STRING);
                break;
            case Constantes.DESCONEXAO_FALHOU:
                JOptionPane.showMessageDialog(this, Constantes.DESCONEXAO_FALHOU_STRING);
                break; 
            case Constantes.JA_DESCONECTADO:
                JOptionPane.showMessageDialog(this, Constantes.JA_DESCONECTADO_STRING);
                break;    
        }
    }

    public String obterNomeServidor() {
        String enderecoServidor = Constantes.ENDERECO_SERVIDOR;
        enderecoServidor = JOptionPane.showInputDialog(this, 
                Constantes.INSIRA_ENDERECO_SERVIDOR, enderecoServidor);
        return enderecoServidor;
    }

    public String obterNomeJogador() {
        return JOptionPane.showInputDialog(Constantes.INSIRA_NOME_JOGADOR);
    }
}
