/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsc.inf.View;

import Presidente.Constantes;
import br.ufsc.inf.Model.Carta;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class TelaMesa extends javax.swing.JFrame {

    protected AtorJogador atorJogador;
   
    
    /**
     * Creates new form TElaMesa
     */
    public TelaMesa(AtorJogador atorJogador) {
        initComponents();
        this.atorJogador = atorJogador;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMesa = new javax.swing.JPanel();
        cartaAdversario1 = new javax.swing.JLabel();
        cartaAdversario2 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuConectar = new javax.swing.JMenu();
        jMenuIniciarPartida = new javax.swing.JMenu();
        jMenuDesconectar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelMesa.setBackground(new java.awt.Color(0, 153, 51));
        painelMesa.setBorder(new javax.swing.border.MatteBorder(null));

        cartaAdversario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufsc/inf/View/imgs/10A.png"))); // NOI18N

        cartaAdversario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufsc/inf/View/imgs/10A.png"))); // NOI18N

        javax.swing.GroupLayout painelMesaLayout = new javax.swing.GroupLayout(painelMesa);
        painelMesa.setLayout(painelMesaLayout);
        painelMesaLayout.setHorizontalGroup(
            painelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMesaLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(cartaAdversario1)
                .addContainerGap(817, Short.MAX_VALUE))
            .addGroup(painelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelMesaLayout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(cartaAdversario2)
                    .addContainerGap(892, Short.MAX_VALUE)))
        );
        painelMesaLayout.setVerticalGroup(
            painelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMesaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(cartaAdversario1)
                .addContainerGap(489, Short.MAX_VALUE))
            .addGroup(painelMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelMesaLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(cartaAdversario2)
                    .addContainerGap(488, Short.MAX_VALUE)))
        );

        jMenuConectar.setText("Conectar");
        jMenuConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuConectarMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuConectar);

        jMenuIniciarPartida.setText("Iniciar Partida");
        jMenuIniciarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuIniciarPartidaMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuIniciarPartida);

        jMenuDesconectar.setText("Desconectar");
        jMenuDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDesconectarMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuDesconectar);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConectarMouseClicked
        // TODO add your handling code here:
        //Informar que Conectar foi clicado
        this.atorJogador.conectar();
    }//GEN-LAST:event_jMenuConectarMouseClicked

    private void jMenuIniciarPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuIniciarPartidaMouseClicked
        // TODO add your handling code here:
        //Informar que Iniciar partida foi clicado
        this.atorJogador.iniciarPartida();
    }//GEN-LAST:event_jMenuIniciarPartidaMouseClicked

    private void jMenuDesconectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDesconectarMouseClicked
        // TODO add your handling code here:
        this.atorJogador.desconectar();
    }//GEN-LAST:event_jMenuDesconectarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartaAdversario1;
    private javax.swing.JLabel cartaAdversario2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConectar;
    private javax.swing.JMenu jMenuDesconectar;
    private javax.swing.JMenu jMenuIniciarPartida;
    private javax.swing.JPanel painelMesa;
    // End of variables declaration//GEN-END:variables

    public void informarResultado(int resultado) {
        switch(resultado){
            case Constantes.CONEXAO_EXITO:
                JOptionPane.showMessageDialog(this, Constantes.CONEXAO_EXITO_STRING);
                break;
            case Constantes.CONEXAO_FALHOU:
                JOptionPane.showMessageDialog(this, Constantes.CONEXAO_FALHOU_STRING);
                break;
            case Constantes.JA_CONECTADO:
                JOptionPane.showMessageDialog(this, Constantes.JA_CONECTADO_STRING);
                break;
            case Constantes.DESCONEXAO_EXITO:
                JOptionPane.showMessageDialog(this, Constantes.DESCONEXAO_EXITO_STRING);
                break;
            case Constantes.DESCONEXAO_FALHOU:
                JOptionPane.showMessageDialog(this, Constantes.DESCONEXAO_FALHOU_STRING);
                break; 
            case Constantes.JA_DESCONECTADO:
                JOptionPane.showMessageDialog(this, Constantes.JA_DESCONECTADO_STRING);
                break;    
            case Constantes.FALTA_CONEXAO:
                JOptionPane.showMessageDialog(this, Constantes.FALTA_CONEXAO_STRING);
                break; 
            case Constantes.JOGO_EM_ANDAMENTO:
                JOptionPane.showMessageDialog(this, Constantes.JOGO_EM_ANDAMENTO_STRING);
                break;   
            case Constantes.INICIAR_PARTIDA_FALHOU:
                JOptionPane.showMessageDialog(this, Constantes.INICIAR_PARTIDA_FALHOU_STRING);
                break; 
            case Constantes.SOLICITADO_INICIO_PARTIDA:
                JOptionPane.showMessageDialog(this, Constantes.SOLICITADO_INICIO_PARTIDA_STRING);
                break;     
        }
    }

    public String obterNomeServidor() {
        String enderecoServidor = Constantes.ENDERECO_SERVIDOR;
        enderecoServidor = JOptionPane.showInputDialog(this, 
                Constantes.INSIRA_ENDERECO_SERVIDOR, enderecoServidor);
        return enderecoServidor;
    }

    public String obterNomeJogador() {
        return JOptionPane.showInputDialog(Constantes.INSIRA_NOME_JOGADOR);
    }

    public void atualizarNomeAdversario(String nome) {
        //TODO ATUALIZAR NOME ADVERSARIO
    }

    void atualizaTelaJogador(List<Carta> cartasJogador, int cartasAdversario, List<Carta> cartasMesa) {
        
    }

    void atualizaTelaAdversario(int cartasJogador, List<Carta> cartasAdversario, List<Carta> cartasMesa) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
